project:
  type: book
  output-dir: ./docs

book:
  title: Lab Protocols
  description: A collection of protocols and notes from wet-lab work.
  sidebar:
    title: Lab Protocols
  author:
    - name: Bhaskar Kumawat
      email: kumawatb@umich.edu
  date: last-modified
  date-format: YYYY
  chapters:
    - index.qmd
    - part: "Synthetic Biology"
      chapters:
        - synbio/p1transduction.qmd
        - synbio/flprecombination.qmd
        - synbio/tsstransform.qmd
    - part: "Microbiology"
      chapters:
        - microbiology/3colorinfection.qmd
        - microbiology/receptorswitchtest.qmd
    - part: "Recipes"
      chapters:
        - recipes/tssbuffer.qmd
  downloads: [pdf]

format:
  html:
    theme: 
      - simplex
      - custom-light.scss
  pdf:
    documentclass: scrreprt
    fontfamily: libertinus
    geometry:
      - right=40mm



