---
date: 10/16/2025
author: Bhaskar Kumawat
citation-location: margin
reference-location: margin
---

# HMW Phage gDNA Extraction (NEB Monarch) {.unnumbered}

**Reagents:** High concentration phage lysate (ideally 10mL, 4mL might also work), Phage precipitation solution (30% PEG-8000, 3M NaCl, filter-sterilized), Resuspension buffer (5mM MgSO4), 10x DNAse I buffer, DNAse I enzyme (2000 U/mL), RNAse A enzyme (20mg/mL), NEB Monarch Kit

**Time required:** 1 day (excluding overnight phage precipitation)


### A. Phage Precipitation

[Day 0]{.aside}

1. Incubate 10mL of phage lysate mixed with 5mL precipitation solution at 4C overnight in a 50mL falcon tube (no shaking). This step precipitates the phage out of the lysate. (4mL lysate with 2mL precipitation solution may also work)

[Day 1]{.aside}

2. Pre-chill a centrifuge to 4C. Centrifuge the precipitated phage lysate at 12,000 rcf for 12 minutes at 4C.

[Day 1]{.aside}

3. Precipitated phage should form a mostly transparent pellet on the bottom of the tube. Carefully pour off supernatant or remove it gently using a pipette. Resuspend the pellet well in 300uL 1x DNAse I Buffer (made by diluting 30uL 10x buffer in 270uL NF Water). Move the final resuspension to a 1.5mL tube.

4. Add 10uL DNAse I + 1uL RNAse A to the resuspended phage, mix by inverting a few times. Incubate at 37C for 30 minutes without shaking. Incubate at 75C for 10 mins to deactivate enzymes.

5. Spin down the tube for 10 seconds in a benchtop centrifuge and transfer supernatant to a 2mL DNA LoBind tube.

6. Add 300uL HMW gDNA Tissue Lysis buffer and 20uL Proteinase K solution to the tube. Incubate samples in a thermal mixer at 56C for 1hr with agitation at 500rpm. 

7. Add 300uL Protein Separation Solution and mix by inverting for 1 minute (each complete inversion should take 3-4 seconds).

8. Centrifuge the tube at 16,000 rcf for 10 minutes and carefully move it to the bench, trying not to agitate the phase boundary. The sample will separate into a large, clear DNA phase and a smaller protein phase at the bottom. Both phases are transparent but the boundary can be seen by holding the tube against a dark background. 

9. Transfer ~800uL of the upper phase containing DNA to another labelled 2mL DNA LoBind Tube (use wide bore 1000uL or 200uL tips for this step). Avoid transferring material from the bottom protein layer.

10. Use clean, ethanol and flame sterilized forceps to add 2 DNA capture beads to the sample in the 2mL tube.

11. Add 550uL isopropanol to the tube, close the cap. Bind the DNA to the beads by inverting slowly and gently by hand for 25-30 times. A full inversion should take 5-6 seconds, with a full inversion completing when tube returns to the upright position. 
    - You should be able to see the DNA precipitate as white filaments after a few inversion. Make sure these filaments are attached to the beads before you conclude this step. If not, invert gently a few more times.

12. After DNA is bound to the beads, discard liquid by pipetting. Avoid removing any of the DNA wrapped on the beads. Make sure to not let the beads dry too much between this and the next step (i.e., add the next buffer as soon as you're done removing the liquid). The process of removing liquid can be carried out in two ways,
    - Keep the tube upright, insert pipette tip, gently push the beads aside until they are up the wall of the tube with liquid at the bottom. Then aspirate the liquid out using the pipette making sure you don't get any DNA into the pipette.
    - Angle the tube so that beads remain at the bottom but liquid reaches the opening of the tube. Pipette liquid from the surface and continue to angle the tube as liquid is removed (tube will be almost horizontal at the end).

13. Add 500uL gDNA wash buffer, close the cap, and mix by inverting tube gently 2-3 times. The gDNA will condense around the beads more tightly. Remove the wash buffer as described in the previous step.

14. Repeat the wash with the gDNA wash buffer as in step 13. After the wash, remove the wash buffer as described in step 12.

15. Place a labelled bead retainer into a monarch collection tube. Pour the beads into the bead retainer and close the cap. Discard the used 2mL tube. 

16. Pulse spin the retainer + collection tube for $\leq$ 1 second in a benchtop centrifuge to remove residual wash buffer from the beads.

17. Separate the bead retainer from the collection tube, pour the beads into a new, labelled 2mL DNA lobind tube. Insert the now empty retainer into a 1.5mL DNA lobind tube for later use. Discard the collection tube.

18. Immediately add 100uL Nuclease free water (prewarmed to 60C) to the glass beads and incubate for 5-10 minutes at 56C in a thermal mixer with agitation at 300rpm. Halfway through this step, ensure the beads are not stuck by tilting the tube almost horizontally and gently shaking.

19. Pour the eluate and glass beads from the 2mL tube into the bead retainer that was inserted into a 1.5mL DNA LoBind tube. Transfer any remaining liquid using a wide bore pipette. Close the cap of the bead retainer. 

20. Centrifuge the bead retainer + 1.5mL tube for 30 seconds at 12,000 rcf to separate the eluted DNA from the glass beads.
 Discard the beads and the retainer.

21. Make sure the DNA is homogeneously dissolved by either incubating at 37C for 30 minutes or for > 24 hours at 4C. The DNA is now ready to be measured using a nanodrop or sent for sequencing.